Work Ahead: WorkAheadManager Class Reference
WorkAheadManager Class Reference
Public Member Functions
loadConfig ($config, $noAutoload=false)
getConfig ()
loadStats ($storageType, $storageData=null)
saveStats ($storageType, $fileName=null)
pageVisit ($visitedPageId, $refererPageId)
Static Public Member Functions
static getInstance ()
Public Attributes
const CONFIG_TYPE_FILE = 0
const CONFIG_TYPE_STRING = 1
const CONFIG_TYPE_SIMPLEXML = 2
const STORAGE_FILE = 0
const STORAGE_JSON = 1
const STORAGE_MYSQL = 2
const LOG_MAX_LEVEL = 5
const LOG_CONF_LOAD = 'Config loaded'
const LOG_CONF_NOT_LOADED = 'Config is not loaded'
const LOG_STATS_AUTOLOAD = 'Stats autoload found'
const LOG_STATS_AUTOLOAD_START = 'Stats autoload started'
const LOG_STATS_AUTOLOAD_END = 'Stats autoload finished'
const LOG_STATS_SAVE = 'Stats save'
const LOG_STATS_SAVE_START = 'Stats save started'
const LOG_STATS_SAVE_END = 'Stats save finished'
const LOG_VISITED_PAGE = 'Visited page'
const LOG_GUESSED_PAGE = 'Guessed next page'
const LOG_PAGE_NOT_GUESSED = 'Page was not guessed'
const LOG_THREAD_FORK = 'Initiating worker thread'
const LOG_THREAD_FORK_START = 'Initiating worker thread start'
const LOG_THREAD_FORK_END = 'Worker thread initiated. Main thread is now continue'
const LOG_THREAD_FORK_DATA = "Thread initial data:\n"
const LOG_PROBABILITY = 'Next page detected with probability'
Private Member Functions
__construct ()
__clone ()
loadMySqlStats ()
saveMySqlStats ()
checkDbConnect ()
getProbability ($visitedPageId)
logOperation ($opString, $params=null)
logLevel1 ($opString, $params=null)
logLevel2 ($opString, $params=null)
logLevel3 ($opString, $params=null)
Private Attributes
$config = null
$stats = null
$dbQueue = array()
$dbConnection = null
$logLevel = 0
Static Private Attributes
static $instance = null
Detailed Description
Definition at line 17 of file WorkAheadManager.class.php.
Constructor & Destructor Documentation
WorkAheadManager::__construct () [private]
Construts the object and prevents misuse due to Singleton pattern
Definition at line 116 of file WorkAheadManager.class.php.
Member Function Documentation
static WorkAheadManager::getInstance () [static]
Returns self instance if has one, or creates new
Returns:
WorkAheadManager
Definition at line 105 of file WorkAheadManager.class.php.
WorkAheadManager::__clone () [private]
Prevents object cloning due to Singleton pattern
Definition at line 124 of file WorkAheadManager.class.php.
WorkAheadManager::loadConfig ($ config, $ noAutoload = false)
Loads a config file
Parameters:
mixed $config Can be XML string, SimpleXMLElement or XML config filename (with path)
bool $noAutoload Specifies not to perform autoloading even if it is specified in config. Used for system purposes
Definition at line 135 of file WorkAheadManager.class.php.
References $config, loadStats(), and logOperation().
WorkAheadManager::getConfig ()
Returns self config
Returns:
SimpleXMLElement
Definition at line 191 of file WorkAheadManager.class.php.
WorkAheadManager::loadStats ($ storageType, $ storageData = null)
Loads statistical data from a storage
Parameters:
int $storageType Storage type
string $storageData Data for STORAGE_JSON (json string) or STORAGE_FILE (file name and path) storage type
Definition at line 202 of file WorkAheadManager.class.php.
References loadMySqlStats(), and logOperation().
Referenced by loadConfig().
WorkAheadManager::saveStats ($ storageType, $ fileName = null)
Saves statistical data to a storage
Parameters:
int $storageType Storage type
string $fileName Filename to save stats for STORAGE_FILE type
Returns:
mixed JSON string or true/false
Definition at line 235 of file WorkAheadManager.class.php.
References logOperation(), and saveMySqlStats().
Referenced by pageVisit().
WorkAheadManager::loadMySqlStats () [private]
Loads stats from MySQL database
Definition at line 265 of file WorkAheadManager.class.php.
References $stats, and checkDbConnect().
Referenced by loadStats().
WorkAheadManager::saveMySqlStats () [private]
Saves stats to MySQL database
Definition at line 295 of file WorkAheadManager.class.php.
References checkDbConnect().
Referenced by saveStats().
WorkAheadManager::checkDbConnect () [private]
Ckecks MySQL connection. Establish one if not connected
Definition at line 307 of file WorkAheadManager.class.php.
Referenced by loadMySqlStats(), and saveMySqlStats().
WorkAheadManager::pageVisit ($ visitedPageId, $ refererPageId)
Runs detection process
Parameters:
string $visitedPageId The current page ID user is now on (according to config site map)
string $referrerPageId The page ID user came from (according to config site map)
Returns:
bool Returns true on success or false on fail
Definition at line 323 of file WorkAheadManager.class.php.
References getProbability(), logOperation(), and saveStats().
WorkAheadManager::getProbability ($ visitedPageId) [private]
Returns the most probable next user move
Parameters:
string $visitedPageId Id of the page user is currenly requested
Returns:
mixed Page Id user will most probably go to. False if cannot guess
Definition at line 469 of file WorkAheadManager.class.php.
References logOperation().
Referenced by pageVisit().
WorkAheadManager::logOperation ($ opString, $ params = null) [private]
Logs operations via error_log function depending on loglevel
Parameters:
string $opString Operation string
string $params Additional string
Definition at line 522 of file WorkAheadManager.class.php.
References $logLevel.
Referenced by getProbability(), loadConfig(), loadStats(), pageVisit(), and saveStats().
WorkAheadManager::logLevel1 ($ opString, $ params = null) [private]
Logs operations for level 1
Parameters:
string $opString Operation string
string $params Additional string
Definition at line 541 of file WorkAheadManager.class.php.
WorkAheadManager::logLevel2 ($ opString, $ params = null) [private]
Logs operations for level 2
Parameters:
string $opString Operation string
string $params Additional string
Definition at line 565 of file WorkAheadManager.class.php.
WorkAheadManager::logLevel3 ($ opString, $ params = null) [private]
Logs operations for level 3
Parameters:
string $opString Operation string
string $params Additional string
Definition at line 589 of file WorkAheadManager.class.php.
Member Data Documentation
const WorkAheadManager::CONFIG_TYPE_FILE = 0
Constants to describe config type
Definition at line 23 of file WorkAheadManager.class.php.
const WorkAheadManager::CONFIG_TYPE_STRING = 1
Definition at line 24 of file WorkAheadManager.class.php.
const WorkAheadManager::CONFIG_TYPE_SIMPLEXML = 2
Definition at line 25 of file WorkAheadManager.class.php.
const WorkAheadManager::STORAGE_FILE = 0
Constants to describe stats storage type
Definition at line 31 of file WorkAheadManager.class.php.
const WorkAheadManager::STORAGE_JSON = 1
Definition at line 32 of file WorkAheadManager.class.php.
const WorkAheadManager::STORAGE_MYSQL = 2
Definition at line 33 of file WorkAheadManager.class.php.
const WorkAheadManager::LOG_MAX_LEVEL = 5
Constants to determine operations to log
Definition at line 39 of file WorkAheadManager.class.php.
const WorkAheadManager::LOG_CONF_LOAD = 'Config loaded'
Definition at line 40 of file WorkAheadManager.class.php.
const WorkAheadManager::LOG_CONF_NOT_LOADED = 'Config is not loaded'
Definition at line 41 of file WorkAheadManager.class.php.
const WorkAheadManager::LOG_STATS_AUTOLOAD = 'Stats autoload found'
Definition at line 42 of file WorkAheadManager.class.php.
const WorkAheadManager::LOG_STATS_AUTOLOAD_START = 'Stats autoload started'
Definition at line 43 of file WorkAheadManager.class.php.
const WorkAheadManager::LOG_STATS_AUTOLOAD_END = 'Stats autoload finished'
Definition at line 44 of file WorkAheadManager.class.php.
const WorkAheadManager::LOG_STATS_SAVE = 'Stats save'
Definition at line 45 of file WorkAheadManager.class.php.
const WorkAheadManager::LOG_STATS_SAVE_START = 'Stats save started'
Definition at line 46 of file WorkAheadManager.class.php.
const WorkAheadManager::LOG_STATS_SAVE_END = 'Stats save finished'
Definition at line 47 of file WorkAheadManager.class.php.
const WorkAheadManager::LOG_VISITED_PAGE = 'Visited page'
Definition at line 48 of file WorkAheadManager.class.php.
const WorkAheadManager::LOG_GUESSED_PAGE = 'Guessed next page'
Definition at line 49 of file WorkAheadManager.class.php.
const WorkAheadManager::LOG_PAGE_NOT_GUESSED = 'Page was not guessed'
Definition at line 50 of file WorkAheadManager.class.php.
const WorkAheadManager::LOG_THREAD_FORK = 'Initiating worker thread'
Definition at line 51 of file WorkAheadManager.class.php.
const WorkAheadManager::LOG_THREAD_FORK_START = 'Initiating worker thread start'
Definition at line 52 of file WorkAheadManager.class.php.
const WorkAheadManager::LOG_THREAD_FORK_END = 'Worker thread initiated. Main thread is now continue'
Definition at line 53 of file WorkAheadManager.class.php.
const WorkAheadManager::LOG_THREAD_FORK_DATA = "Thread initial data:\n"
Definition at line 54 of file WorkAheadManager.class.php.
const WorkAheadManager::LOG_PROBABILITY = 'Next page detected with probability'
Definition at line 55 of file WorkAheadManager.class.php.
WorkAheadManager::$instance = null [static, private]
Definition at line 61 of file WorkAheadManager.class.php.
WorkAheadManager::$config = null [private]
Definition at line 68 of file WorkAheadManager.class.php.
Referenced by loadConfig().
WorkAheadManager::$stats = null [private]
Definition at line 75 of file WorkAheadManager.class.php.
Referenced by loadMySqlStats().
WorkAheadManager::$dbQueue = array() [private]
Definition at line 83 of file WorkAheadManager.class.php.
WorkAheadManager::$dbConnection = null [private]
Definition at line 91 of file WorkAheadManager.class.php.
WorkAheadManager::$logLevel = 0 [private]
Definition at line 98 of file WorkAheadManager.class.php.
Referenced by logOperation().
The documentation for this class was generated from the following file:
lib/classes/WorkAheadManager.class.php